packages:
  - "core-lint"
  - "core-ui"
  - "portal"
  - "pylon"
  - "scripts"

linkWorkspacePackages: true
preferWorkspacePackages: true

overrides:
  is-arrayish: "0.2.1"
  tinyglobby: "0.2.16"
  "@pylonline/core-lint": "workspace:*"
  "@pylonline/core-ui": "workspace:*"

allowBuilds:
  esbuild: true
  sharp: true
  workerd: true

minimumReleaseAgeExclude:
  - miniflare@4.20260520.0
  - wrangler@4.93.1
